#!/bin/bash
# Structure Refactoring Script
# Generated by BrownKit
#
# ⚠️  WARNING: This script only moves files!
# ⚠️  You MUST update imports manually after running this!
#
# Recommended: Use IDE refactoring instead of this script.

set -e  # Exit on error

echo "🏗️  Moving files to standard structure..."
echo ""
echo "⚠️  WARNING: Imports will NOT be updated automatically!"
echo "⚠️  You must fix import statements manually after this script completes."
echo ""
read -p "Continue? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 0
fi


echo ""
echo "✓ File moves complete!"
echo ""
echo "⚠️  IMPORTANT: You must now update import statements manually!"
echo "   Or use your IDE's refactoring tools to fix imports."
echo ""
echo "Verify structure after fixing imports:"
echo "  brownfield structure --verify"
