name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install lizard

    - name: Run ruff linter
      run: |
        ruff check src/ tests/

    - name: Check ruff formatting
      run: |
        ruff format --check src/ tests/

    - name: Run pylint
      run: |
        pylint src/brownfield/ --rcfile=.pylintrc
      continue-on-error: true

    - name: Run mypy type checking
      run: |
        mypy src/brownfield/

    - name: Check code complexity
      run: |
        lizard src/brownfield -l python --CCN 10
